#!/usr/bin/python3
from sys import argv;

def asm(s: str) -> str:
  st = ""; i = 0;
  s = s.replace("11", "4");
  while (s[i] in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"):
    st += s[i].lower();
    i += 1;
  while (i < len(s)):
    if (s[i] == "0"):
      st += " $i";
    elif (s[i] == "1"):
      st += " %r";
    elif (s[i] == "2"):
      st += " [$i]";
    elif (s[i] == "3"):
      st += " [%r]";
    elif (s[i] == "4"):
      st += " %rc";
    else:
      print("invalid");
      exit(1);
    i += 1;
  return st;

for i in argv[1:]:
  print(asm(i));

