#!/usr/bin/python3
import sys;

def main(argc: int, argv: list):
  def_tag: str = "com/";
  if (argc < 4):
    print("gload: not enough arguments");
    return 1;
  with open(argv[1], "rb") as fl:
    dest = bytearray(fl.read());
  with open(argv[2], "rb") as fl:
    src = fl.read();
  startaddr = dest.find(0xF7);
  dest[startaddr] = 0xF1;
  startaddr += 1;
  for byte in argv[3].encode():
    dest[startaddr] = byte;
    startaddr += 1;
  for byte in b"\xF2"+def_tag.encode()+b"\xF2\x00":
    dest[startaddr] = byte;
    startaddr += 1;

  for byte in src:
    if (byte < 0xE0):
      dest[startaddr] = byte;
      startaddr += 1;
    else:
      dest[startaddr] = 0xE0;
      dest[startaddr+1] = (byte - 0xE0) % 256;
      startaddr += 2;
  dest[startaddr] = 0xF1;
  startaddr += 1;
  dest[startaddr] = 0xF7;
  startaddr += 1;
  with open(argv[1], "wb") as disk:
    disk.write(dest);

  return 0;

sys.exit(main(len(sys.argv), sys.argv));
