#!/usr/bin/bash
set -e

if [ $# = 0 ]; then
  printf "No disk given\n";
  exit 1;
fi

printf "Formatting %s to GovnFS ...\n" $1
./mkfs.govnfs $1
printf "Loading GovnOS into the boot sector of %s ...\n" $1
./gboot $1 govnos/boot.bin > /dev/null
printf "Done!\n"

