#!/bin/bash

print_state() {
  printf "Building $1...\n"
}

completed_state() {
  printf "\nCompilation finished!\n"
}

build_state() {
  print_state $1
  cd $2
  ./build > /dev/null 2>&1
  cd - > /dev/null
}

mkdir -p bin
build_state "gc16"        "core/"
build_state "gasman"      "core/gasman/"
build_state "gboot"       "core/gboot/"
build_state "ugovnfs"     "core/ugovnfs/"
build_state "GovnOS"      "govnos/"
completed_state

