#!/bin/bash

set -e

if [ $# = 0 ]; then
  printf "No disk name and size given\n";
  exit 1;
fi

if [ $# = 1 ]; then
  printf "No size given\n";
  exit 1;
fi

if [ -f $1 ]; then
    rm -f $1
fi

touch $1
truncate -s $2 $1

printf "Disk $1 successfully created\n" $1

