#!/bin/bash
set -e

if [ $# = 0 ]; then
  printf "No disk given\n";
  exit 1;
fi

printf "Formatting %s to GovnFS ...\n" $1
./scripts/mkfs.govnfs $1
printf "Loading GovnOS into the boot sector of %s ...\n" $1
./bin/gboot $1 govnos/boot.bin
printf "Done!\n"

